# Generated by Django 3.0 on 2025-03-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_auto_20250312_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
    ]
