# Generated by Django 3.0 on 2025-03-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0003_auto_20250312_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
