name: CI/CD Pipeline

on:
  push:
    branches: [master, qa]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 pytest pytest-cov

      - name: Collect static files
        run: python manage.py collectstatic --noinput

      - name: Lint with flake8
        run: flake8 .

      - name: Run tests and check coverage
        run: pytest --cov=. --cov-fail-under=80

  docker:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/oc-lettings:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/oc-lettings:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
